### ISSUE TITLE
Not a bug - I ported to Tiva Launchpad and slightly tweaked it FYI

### ISSUE THREAD

**Issue by raplin** [Frans-Willem/CsrUsbSpiDeviceRE#2]
Hi,
Just FYI this code didn't build on the new "Tiva C Launchpad" which is the replacement for Stellaris (TI appear to be renaming everything and tweaking the product line).

The newer "Tiva C Launchpad" (EK-TM4C123GXL) is $12; I don't think the "Stellaris Launchpad" officially exists any more.

I forked this repo, hacked it to compile on TivaWare, and added a "Turbo mode" option hack (which works for me; gives 2x speed programming, YMMV)

I also provided a binary so people can just use the TI Flash programmer instead downloading a couple of gig of IDEs etc, if they just want a clone programmer with no hassle.

https://github.com/raplin/CsrUsbSpiDeviceRE

I didn't do a pull request as I didn't figure out the #ifdef's required to make it build on both Stellaris and Tivaware -  but it may be useful to people with the Tiva C board; if you like you could link to my repo or whatever you feel like. :-)

Many, many thanks for your hard work Frans-willem - awesome job. This device works perfectly for me with all the usual CSR tools.

**Comment by Frans-Willem** [comment]
Hi Richard,

Great to hear!
I'll put up a little note on the Readme, and will probably order a Tiva 
C launchpad to check out :p

On the turbo mode: I remember I made an estimate on the speed the 
original programmer would put out, and recreate that.
I'm fairly sure it'll work faster, but at the time of writing this I had 
already tried several different incarnations of a similar project on 
Arduino, and having everything fail at some point, I opted to make this 
version as close to the original programmer as I could possibly be.
Faster will probably work for 90% of the use cases, just make sure 
there's a switch somewhere to set it back to slower for the other 10% :)

I'll also take a look to see if it'll be possible to create one version 
that would compile on both Stellaris as well as Tiva C launchpad, but 
that might take a while ;-)

Finally, a quick request back: If you do end up actually writing stuff 
for these BlueCore chips, please share your knowledge. I put a lot of 
work into gettting the programmer working, but didn't have enough time 
to actually test some different code on the device itself. I've got 10 
of these chips lying around to mess with some day, and I'd love to turn 
them into actual projects! :D

Anyway, great work, and do keep me posted on anything new,

Frans-Willem

P.S. Feel free to e-mail me directly at fw@hardijzer.nl in the future.

**Comment by nissimzur** [comment]
Thank you

Kind regards,
Dr. Nissim Zur
Bluetooth Smart, IoT expert

 http://www.elinistech.com/ CTO Elinistech
